repos:
  # pre-commit install
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: detect-private-key

  # pre-commit install
  - repo: https://github.com/crate-ci/typos
    rev: v1.16.11
    hooks:
      - id: typos
        args: [--config, .config/.typos.toml]
        exclude: ".*gen"

  # pre-commit install --hook-type commit-msg
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args:
          [
            build,
            chore,
            ci,
            deploy,
            docs,
            feat,
            fix,
            perf,
            refactor,
            revert,
            style,
            test,
          ]

  # pre-commit install
  - repo: https://github.com/yoheimuta/protolint
    rev: v0.46.0
    hooks:
      - id: protolint
        args: [src/proto]
