version: "3"

includes:
  tools:
    taskfile: "../tools/Taskfile.yaml"
    internal: true
    dir: "../tools"

tasks:
  pre-commit:install-tools:
    deps:
      - "tools:install-protoc-gen-go"
      - "tools:install-protoc-gen-go-grpc"
