version: "3"

vars:
  PROTOC_VERSION: libprotoc 24.3

tasks:
  check-protoc:
    cmd: echo "please install protoc {{.PROTOC_VERSION}}"
    status: ["which protoc"]

  download-tools:
    internal: true
    cmd: go mod download
    run: once

  install-protolint:
    internal: true
    cmd: go install github.com/yoheimuta/protolint/cmd/protolint
    deps: ["download-tools"]
    status: ["which protolint"]

  install-protoc-gen-go:
    internal: true
    cmd: go install google.golang.org/protobuf/cmd/protoc-gen-go
    deps: ["download-tools"]
    status: ["which protoc-gen-go"]

  install-protoc-gen-go-grpc:
    internal: true
    cmd: go install google.golang.org/grpc/cmd/protoc-gen-go-grpc
    deps: ["download-tools"]
    status: ["which protoc-gen-go-grpc"]

  install-oapi-codegen:
    internal: true
    cmd: go install github.com/deepmap/oapi-codegen/cmd/oapi-codegen
    deps: ["download-tools"]
    status: ["which oapi-codegen"]

  install-tools:
    deps:
      - "check-protoc"
      - "install-protolint"
      - "install-protoc-gen-go"
      - "install-protoc-gen-go-grpc"
      - "install-oapi-codegen"
    desc: Install all tools
