name: build

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  GO_VERSION: 1.21

jobs:
  go-mod-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Install golang
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for missing dependencies
        run: |
          go mod tidy
          git diff --exit-code

      - name: Download dependencies
        run: |
          go mod download

      - name: Verify dependencies
        run: |
          go mod verify

  proto-generate-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Install golang
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install protoc
        uses: arduino/setup-protoc@v2.0.0
        with:
          version: "24.2"

      - name: Install go-task
        uses: arduino/setup-task@v1
        with:
          version: 3.x

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate proto files
        run: |
          task go:proto:gen
          git diff --exit-code


  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - name: Install golang
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build code
        run: go build -v ./...
