name: lint

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run [typos]
        uses: crate-ci/typos@v1.16.8
        with:
          config: .typos.toml

  pre-commit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        hook_id:
          [
            trailing-whitespace,
            end-of-file-fixer,
            check-yaml,
            detect-private-key,
          ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4

      - name: Run [${{ matrix.hook_id }}]
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: ${{ matrix.hook_id }} --all-files

  protolint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run [protolint]
        uses: plexsystems/protolint-action@v0.7.0
        with:
          configDirectory: ./
