name: pull-request

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  PROTOC_VERSION: "24.2"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run typos
        uses: crate-ci/typos@v1.16.11
        with:
          config: .config/.typos.toml

  lint-proto:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run protolint
        uses: plexsystems/protolint-action@v0.7.0
        with:
          configDirectory: .

  lint-pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install golang
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod
        cache: true
        cache-dependency-path: |
          tools/go.sum

    - name: Install Python
      uses: actions/setup-python@v4

    - name: Install go-task
      run: make install-gotask

    - name: Install tools
      run: task pre-commit:install-tools
      working-directory: ci

    - name: Run pre-commit
      uses: pre-commit/action@v3.0.0
      with:
        extra_args: --all-files

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install golang
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: |
            go.sum
            tools/go.sum

      - name: Install protoc
        uses: arduino/setup-protoc@v2.1.0
        with:
          version: $PROTOC_VERSION
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install go-task
        run: make install-gotask

      - name: Check for missing dependencies
        run: |
          go mod tidy
          git diff --exit-code

      - name: Download dependencies
        run: |
          go mod download

      - name: Verify dependencies
        run: |
          go mod verify

      - name: Generate proto files
        run: |
          task go:proto:gen
          git diff --exit-code

      - name: Build code
        run: |
          go build -v ./...
